name: Draw keymap
on:
  workflow_dispatch: # can be triggered manually
  push:
    paths:
      - "config/corne.keymap"
      - "config/knucklehead/*.dtsi"
      - "keymap-drawer/config.yaml"
      - ".github/workflows/draw.yml"

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@dev
    permissions:
      contents: write
    with:
      install_branch: "dev" # branch to install keymap-drawer from
      keymap_patterns: "config/corne.keymap" # path to the keymaps to parse
      config_path: "keymap-drawer/config.yaml" # config file, ignored if it doesn't exist
      output_folder: "keymap-drawer" # path to save produced SVGs in the existing folder
      extra_keymap_yaml: "corne:'keymap-drawer/combos.yaml'"
      commit_message: "chore(draw): keymap"
      fail_on_error: true
